from botrayado.handlers import start
from botrayado.handlers import donate
from botrayado.handlers import _help
from botrayado.handlers import joke
from botrayado.handlers import schedule
from botrayado.handlers import menu
from botrayado.handlers import config
from botrayado.handlers import null
from botrayado.handlers import admin
from botrayado.handlers import aliases