from botrayado.keyboards.menu_kb import START_KB
from botrayado.keyboards.schedule_kb import GROUP_BFI_KB
from botrayado.keyboards.schedule_kb import GROUP_BVT_KB
from botrayado.keyboards.schedule_kb import GROUP_BST_KB
from botrayado.keyboards.schedule_kb import GROUP_BEI_KB
from botrayado.keyboards.schedule_kb import GROUP_BIB_KB
from botrayado.keyboards.schedule_kb import GROUP_BAP_KB
from botrayado.keyboards.schedule_kb import GROUP_BMP_KB
from botrayado.keyboards.schedule_kb import GROUP_BUT_KB
from botrayado.keyboards.schedule_kb import GROUP_ZRC_KB
from botrayado.keyboards.schedule_kb import GROUP_BRT_KB
from botrayado.keyboards.schedule_kb import GROUP_BIK_KB
from botrayado.keyboards.schedule_kb import GROUP_BEE_KB
from botrayado.keyboards.schedule_kb import GROUP_BER_KB
from botrayado.keyboards.schedule_kb import GROUP_BBI_KB
from botrayado.keyboards.schedule_kb import GROUP_BIN_KB
from botrayado.keyboards.schedule_kb import FACULTIES_KB
from botrayado.keyboards.schedule_kb import STREAM_IT_KB
from botrayado.keyboards.schedule_kb import STREAM_TSEIMK_KB
from botrayado.keyboards.schedule_kb import STREAM_RIT_KB
from botrayado.keyboards.schedule_kb import STREAM_KIIB_KB
from botrayado.keyboards.schedule_kb import STREAM_SISS_KB
from botrayado.keyboards.schedule_kb import DAYS_OF_WEEK_KB
from botrayado.keyboards.schedule_kb import CURRENT_OR_NEXT_WEEK_KB